### ISSUE TITLE
Random disk read optimization example

### ISSUE THREAD

**Issue by nponeccop** [streamcode9/node-discrete-spsa#5]
- [x] Implement an abraxas worker that reads a random page of size X from disk using `fs.read`
- [x] Run 10000 tasks and measure the time using difference of `Date.now()`. Preheat worker etc but without `benchmark` and statistics. You don't need to average the time over many runs.
- [x] Find optimal `[maxJobs, maxQueued, pageSize]` using `iterate`

**Comment by streamcode9** [comment]
If [maxJobs, maxQueued, pageSize] = [100, 100, 100], speed = 63.1328 for 10000 tasks

**Comment by streamcode9** [comment]
For jobsCount=1000 with 50 iterations: maxJobs = 10, maxQueued= 49, pageSize= 258

**Comment by nponeccop** [comment]
The bench should measure and optimize performance of reads, not performance of file opening and reading same chunk over and over from disk cache. So the file should be opened once and not once per reading operation. Page size and page number should be indicated in the job payload in JSON format.
- [ ] open the file once
- [ ] pass page number and page count to the worker
- [ ] calculate file offset from page number and page size
- [ ] Preheating is not necessary (my mistake)
- [ ] pushJobs should generate random page numbers
